name: livef_ootbal_lticket
description: "Live Football Ticket"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+6
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  flutter_colorpicker: ^1.0.3
  flutter_svg: ^2.0.9
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: assests/lg.png
  remove_alpha_ios: true


flutter:
  uses-material-design: true
